version: '3'
services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379"
    command: [
      "bash", "-c",
      '
       docker-entrypoint.sh
       --requirepass password
      '
    ]
    volumes:
      - redis-data:/data
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/bookmark-mini:cached
      - bundle:/bundle:cached
      - /bookmark-mini/log
      - /bookmark-mini/tmp/
      - /bookmark-mini/.git
      - /bookmark-mini/vendor
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mailcatcher
    env_file:
      - ./.env
  worker:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/bookmark-mini:cached
      - bundle:/bundle:cached
      - /bookmark-mini/log
      - /bookmark-mini/tmp/
      - /bookmark-mini/.git
      - /bookmark-mini/vendor
    depends_on:
      - redis
      - db
    env_file:
      - ./.env

volumes:
  db-data:
    driver: local
  bundle:
    driver: local
  redis-data:
    driver: local
